[Feat] 장바구니, 주문내역, 내활동, 최근 본 상품 제작
cacao-friends-shop/cacao-friends-shop_client pull request #57
Opened 2021-05-04 13:08 UTC by yg-0103

2021-05-04 17:49 UTC, iamkjw77 requested changes

2021-05-04 17:49 UTC, iamkjw77 commented on src/App.tsx
> +      <ActivityListItem
테스트 코드는 지워주세용~

2021-05-04 17:49 UTC, iamkjw77 commented on src/components/molecules/ActivityListItem/index.tsx
> +        <span>게시물을 좋아했습니다</span>
댓글을 작성한 경우는 어떻게 처리되는 건가요?

2021-05-04 17:49 UTC, iamkjw77 commented on src/pages/Cart/template/index.tsx
> +const CartTemplate = () => {
CartTemplate 대신에 template로 사용하는  것은 어떨까요?

2021-05-05 04:25 UTC, yg-0103 commented on src/components/molecules/ActivityListItem/index.tsx
> +        <span>게시물을 좋아했습니다</span>
서버완성되면 다 수정할예정입니다 ^^;;

2021-05-05 04:26 UTC, yg-0103 commented on src/pages/Cart/template/index.tsx
> +const CartTemplate = () => {
그러면 뭐에 템플릿인지 헷갈리지 않을까요,..?

2021-05-05 05:11 UTC, merged